import type { Metadata } from "next";
import { Providers } from "./providers";
import { Header } from "@/components/shared/header/Header";
import { Footer } from "@/components/shared/footer/Footer";
import { Grid } from "@chakra-ui/react";
import { SidebarNavigation } from "@/components/shared/Sidebar/SidebarNavigation";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          <Grid
            templateColumns={{
              base: "1fr",
              md: "1fr 3fr",
            }}
            bg="purple.dark"
          >
            <SidebarNavigation />
            {children}
          </Grid>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
