import type { Metadata } from "next";
import { Providers } from "./providers";
import { Grid, Hide } from "@chakra-ui/react";
import { Sidebar } from "@/components/shared/Sidebar/Sidebar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Grid
            templateColumns={{
              base: "1fr",
              md: "1fr 3fr",
            }}
            bg="purple.500"
          >
            <Sidebar />
            {children}
          </Grid>
        </Providers>
      </body>
    </html>
  );
}
